### ISSUE TITLE
Enable CORS so postings can be used on other sites

### ISSUE THREAD

**Issue by mrcarlosrendon** [GSA/jobs_api#2]
By adding the following HTTP header to responses, it is possible to embed the jobs data on other websites easily with Javascript.

Access-Control-Allow-Origin: *

For more information see: 
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
http://www.w3.org/TR/cors/

**Comment by TheConnMan** [comment]
Or add JSONP support. Currently the API is unusable by server-less sites.

**Comment by loren** [comment]
CORS support has been added.
https://github.com/GSA/jobs_api/commit/4381367a22b669aad656c90aeb2143aefa8b8858

**Comment by btholt** [comment]
I'm making requests against https://api.usa.gov/jobs/search.json?query=nursing+jobs and I'm not seeing CORS headers on it. Am I missing something obvious here?

**Comment by loren** [comment]
Turns out I missed something obvious: deploying this last change to production after merging the pull request. Sorry for the confusion there.

`curl -I -H 'Origin: http://www.example.com' 'https://api.usa.gov/jobs/search.json?query=nursing+jobs'`
