### ISSUE TITLE
Is the data.usajobs.gov Jobs API shutting down?

### ISSUE THREAD

**Issue by dannguyen** [GSA/jobs_api#4]
Via the homepage:

https://data.usajobs.gov/

> - The JOBS REST Service will be removed in release 5.3 in January, 2016

It seems that the API is moving from unauthenticated access to a system in which you have to submit a request for an API key: https://developer.usajobs.gov/APIRequest/Index 

(the process is automated, thankfully)

I haven't gone through all the new docs but I assume the API will have a different schema.

I'm going to post a screenshot of the page because of how confusingly labeled that text is, in relation to the rest of the page:

![image](https://cloud.githubusercontent.com/assets/121520/12560121/d18a7a36-c34d-11e5-9480-a9e46433fa93.png)

**Comment by noremmie** [comment]
Hi Dan. Data.USAJOBS.gov is a separate entity from the DigitalGov Search Jobs API. Although the DigitalGov Search Jobs API does use Data.USAJOBS.gov as a source for jobs info, it does so via internal channels and not through their API. So this Data.USAJOBS.gov API change shouldn't impact the DigitalGov Search Jobs API.

If you're using the DigitalGov Search Jobs API directly, then you shouldn't have anything to worry about. If you are instead using Data.USAJOBS.gov directly, you will need to follow their instructions to update the way you access it.

**Comment by dannguyen** [comment]
@noremmie Great! All I needed to know, thanks! I'm using the API for a class and just wanted to make sure I wouldn't be pointing students to something that might change in the near foreseeable future
